# Generated by Django 3.2 on 2023-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20220520_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'production'), (1, 'evaluation')]),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(0, 'javascript_sdk'), (1, 'ios_sdk'), (2, 'android_sdk')]),
        ),
    ]
